### ISSUE TITLE
Adding $on.hover to `Box` throws confusing AssertionError

### ISSUE THREAD

**Issue by craiglabenz** [conceptadev/mix#372]
### Package version

1.2.0

### Flutter version

$ flutter --version
Flutter 3.23.0-13.0.pre.102 • channel master • git@github.com:flutter/flutter.git
Framework • revision cd8e84f465 (5 weeks ago) • 2024-06-05 08:02:53 -0700
Engine • revision 11a32d43e3
Tools • Dart 3.5.0 (build 3.5.0-222.0.dev) • DevTools 2.36.0

### Steps to reproduce

1. Take sample code (using a `Box` widget) from fluttermix.com
2. Add `$on.hover()` declaration to its `Style`
3. Run app (app crashes)
4. Replace `Box` with `PressableBox`
5. Run app again (now it works)

### Expected results

The app should render and use the `hover` effect.

If `hover`'s incompatibility with `Box` is known and intended, there should be a more helpful error message.

### Actual results

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Box(dirty):
Unable to find an instance of PressableState...
'package:mix/src/widgets/widget_state/widget_state.dart':
Failed assertion: line 55 pos 12: 'result != null'

The relevant error-causing widget was:
  Box Box:file:///Users/craiglabenz/Dev/fdr/mix_sample/lib/main.dart:77:12

When the exception was thrown, this was the stack:
#2      WidgetStateModel.of (package:mix/src/widgets/widget_state/widget_state.dart:55:12)
#3      WidgetStateModel.hoverOf (package:mix/src/widgets/widget_state/widget_state.dart:86:12)
#4      OnHoverVariant.when (package:mix/src/widgets/widget_state/widget_state_variant.dart:39:55)
#5      _applyVariants (package:mix/src/core/factory/mix_data.dart:157:35)
#6      applyContextToVisualAttributes (package:mix/src/core/factory/mix_data.dart:142:13)
#7      new MixData.create (package:mix/src/core/factory/mix_data.dart:37:27)
#8      Style.of (package:mix/src/core/factory/style_mix.dart:176:47)
#9      StyledWidget.withMix (package:mix/src/core/styled_widget.dart:52:23)
#10     Box.build (package:mix/src/specs/box/box_widget.dart:53:12)
#11     StatelessElement.build (package:flutter/src/widgets/framework.dart:5690:49)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5620:15)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5336:7)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5602:5)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5596:5)
...     Normal element mounting (7 frames)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#23     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7038:36)
#24     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7050:32)
...     Normal element mounting (28 frames)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#53     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7038:36)
#54     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7050:32)
...     Normal element mounting (128 frames)
#182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#183    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7038:36)
#184    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7050:32)
...     Normal element mounting (188 frames)
#372    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#373    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7038:36)
#374    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7050:32)
...     Normal element mounting (552 frames)
#926    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#927    Element.updateChild (package:flutter/src/widgets/framework.dart:3966:18)
#928    _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:441:16)
#929    _RawViewElement.mount (package:flutter/src/widgets/view.dart:464:5)
...     Normal element mounting (15 frames)
#944    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4471:16)
#945    Element.updateChild (package:flutter/src/widgets/framework.dart:3966:18)
#946    RootElement._rebuild (package:flutter/src/widgets/binding.dart:1605:16)
#947    RootElement.mount (package:flutter/src/widgets/binding.dart:1574:5)
#948    RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1527:18)
#949    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#950    RootWidget.attach (package:flutter/src/widgets/binding.dart:1526:13)
#951    WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1265:27)
#952    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1247:5)
#953    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1233:7)
#957    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 5 frames from class _AssertionError, class _Timer, and dart:async-patch)
```

### Code sample

<details open><summary>Code sample</summary>

```dart
class MixWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    final style = Style(
      $box.height(100),
      $box.width(300),
      $box.margin(10, 20),
      $box.color.blue(),
      $box.borderRadius(10),
      $box.padding(10),
      $box.border(
        color: Colors.black,
        width: 1,
        style: BorderStyle.solid,
      ),
      $on.hover(
        $box.color.red(),
      ),
    );

    return Box(
      style: style,
      child: const Text('Hello'),
    );
  }
}
```

Replacing `Box` with `PressableBox` helps the app run successfully again, but this currently requires active investigation from a developer to figure out. Also, I'm not actually sure whether that is the correct solution!

</details>

**Comment by leoafarias** [comment]
@craiglabenz This makes sense. We are looking into ways to apply some of the widget states automatically to the box and merge them. In the meantime, we will definitely improve the error message.
